
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SAVE_SETTINGS_DONE = 'SAVE_SETTINGS_DONE';
export const ERROR_SAVE_SETTINGS = 'ERROR_SAVE_SETTINGS';

export const LOAD_TURNED_ON_HEATERS = 'LOAD_TURNED_ON_HEATERS';
export const LOAD_TURNED_ON_HEATERS_DONE = 'LOAD_TURNED_ON_HEATERS_DONE';
export const ERROR_LOAD_TURNED_ON_HEATERS = 'ERROR_LOAD_TURNED_ON_HEATERS';

export const LOAD_ROOM_TEMPERATURES =  'LOAD_ROOM_TEMPERATURES';
export const LOAD_ROOM_TEMPERATURES_DONE =  'LOAD_ROOM_TEMPERATURES_DONE';
export const ERROR_LOAD_ROOM_TEMPERATURES = 'ERROR_LOAD_ROOM_TEMPERATURES';

export const LOAD_OPEN_WINDOWS = 'LOAD_OPEN_WINDOWS';
export const LOAD_OPEN_WINDOWS_DONE = 'LOAD_OPEN_WINDOWS_DONE';
export const ERROR_LOAD_OPEN_WINDOWS = 'ERROR_LOAD_OPEN_WINDOWS';

export const LOAD_ROOM_MAP = 'LOAD_ROOM_MAP';
export const LOAD_ROOM_PLAN_DONE = 'LOAD_ROOM_PLAN_DONE';
export const ERROR_LOAD_ROOM_PLAN = 'ERROR_LOAD_ROOM_PLAN';
