//for htw showtime

export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SAVE_SETTINGS_DONE = 'SAVE_SETTINGS_DONE';
export const ERROR_SAVE_SETTINGS = 'ERROR_SAVE_SETTINGS';

export const LOAD_ALL_THINGS = 'LOAD_ALL_THINGS';
export const LOAD_ALL_THINGS_SUCCESS = 'LOAD_ALL_THINGS_SUCCESS';
export const ERROR_LOAD_ALL_THINGS = 'ERROR_LOAD_ALL_THINGS';

export const START_POLLING = 'START_POLLING';
export const CANCEL_POLLING = 'CANCEL_POLLING';
