"""empty message

Revision ID: c30f16f5d9f5
Revises: e13d1926dcaf
Create Date: 2019-06-05 22:41:57.460564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30f16f5d9f5'
down_revision = 'e13d1926dcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('window')
    op.drop_table('room')
    op.drop_table('heater')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heater',
    sa.Column('heater_id', sa.INTEGER(), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('coord_x', sa.FLOAT(), nullable=True),
    sa.Column('coord_y', sa.FLOAT(), nullable=True),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('heater_id')
    )
    op.create_table('room',
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('coord_x', sa.FLOAT(), nullable=True),
    sa.Column('coord_y', sa.FLOAT(), nullable=True),
    sa.Column('office_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office.office_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('window',
    sa.Column('window_id', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.BOOLEAN(), nullable=True),
    sa.Column('coord_x', sa.FLOAT(), nullable=True),
    sa.Column('coord_y', sa.FLOAT(), nullable=True),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('state IN (0, 1)'),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('window_id')
    )
    # ### end Alembic commands ###
