"""empty message

Revision ID: e13d1926dcaf
Revises: 
Create Date: 2019-06-05 18:48:43.459869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13d1926dcaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office',
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('office_name', sa.String(length=64), nullable=True),
    sa.Column('office_address', sa.String(length=128), nullable=True),
    sa.Column('path_to_floorplan', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('office_id')
    )
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=True),
    sa.Column('coord_y', sa.Float(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office.office_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('heater',
    sa.Column('heater_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=True),
    sa.Column('coord_y', sa.Float(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('heater_id')
    )
    op.create_table('window',
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=True),
    sa.Column('coord_y', sa.Float(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('window_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('window')
    op.drop_table('heater')
    op.drop_table('room')
    op.drop_table('office')
    # ### end Alembic commands ###
